# Generated by Django 5.0.14 on 2026-08-29 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Encomenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_rastreio', models.CharField(max_length=30, unique=True)),
                ('status_atual', models.CharField(choices=[('em_transito', 'Em trânsito'), ('aguardando_retirada', 'Aguardando retirada'), ('retirada_confirmada', 'Retirada confirmada'), ('devolvido', 'Devolvido')], default='aguardando_retirada', max_length=25)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('prazo_guarda', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'encomendas',
            },
        ),
        migrations.CreateModel(
            name='Movimentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField()),
                ('tipo_evento', models.CharField(max_length=50)),
                ('descricao', models.TextField()),
            ],
            options={
                'db_table': 'movimentacoes',
                'ordering': ['data_hora'],
            },
        ),
    ]
