# Generated by Django 5.0.14 on 2026-08-29 19:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('encomendas', '0001_initial'),
        ('pontos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='encomenda',
            name='destinatario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='encomendas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='encomenda',
            name='ponto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='encomendas', to='pontos.pontoretirada'),
        ),
        migrations.AddField(
            model_name='movimentacao',
            name='encomenda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentacoes', to='encomendas.encomenda'),
        ),
    ]
